#!/usr/bin/env bash

#soji dim
soji log "break" "${1:-break}"

os_x=`uname -a | fgrep -i 'Darwin'`
if [ "$os_x" != "" ]; then
    crontab -l | { cat; echo "`date -v +5M +'%M %H %d %m *'` env PATH="${PATH}" soji bright"; } | crontab -
#    crontab -l | { cat; echo "`date -v +10M +'%M %H %d %m *'` soji bright"; } | crontab -
#    crontab -l | { cat; echo "`date -v +10M +'%M %H %d %m *'` soji notify 'Break over!'"; } | crontab -
else
    crontab -l | { cat; echo "`date +'%M %H %d %m *' --date '+10 min'` soji bright"; } | crontab -
fi

soji callback "break"
