#!/usr/bin/env bash

#prompt
ESC_SEQ="\x1b[38;5;"
RED=$ESC_SEQ"1;31m"
YELLOW=$ESC_SEQ"1;33m"
GREEN=$ESC_SEQ"1;32m"
WHITE=$ESC_SEQ"1;97m"
BLUE=$ESC_SEQ"1;34m"
AQUA=$ESC_SEQ"1;36m"
NOCOLOR="$ESC_SEQ\1;0m"

todays_note_file=`soji note-path log`
pom_count=`cat $todays_note_file 2> /dev/null | grep -i "** start" | wc -l`
poms=""
if [ $pom_count -lt 4 ]; then
  poms="$WHITE pomodoros $RED $pom_count"
elif [ $pom_count -lt 8 ]; then
  poms="$WHITE pomodoros $YELLOW $pom_count"
else
  poms="$WHITE pomodoros $GREEN $pom_count "
fi

water_count=`cat $todays_note_file 2> /dev/null | grep -i "** water" | wc -l`
waters=""
if [ $water_count -lt 2 ]; then
  waters="$WHITE waters $RED $water_count"
elif [ $water_count -lt 4 ]; then
  waters="$WHITE waters $YELLOW $water_count"
else
  waters="$WHITE waters $BLUE $water_count"
fi

lunch=""
cat $todays_note_file 2> /dev/null | grep -i "** lunch" &> /dev/null
if [[ $? == 0 ]]; then
  lunch="$WHITE lunch $GREEN[✔]"
else
  lunch="$WHITE lunch $RED[✘]"
fi

meditation=""
cat $todays_note_file 2> /dev/null  | grep -i "** Meditation" &> /dev/null
if [[ $? == 0 ]]; then
  meditation="$WHITE meditation $GREEN[✔]"
else
  meditation="$WHITE meditation $RED[✘]"
fi

journal=""
if [ -e `soji note-path journal` ]; then
  journal="$WHITE journal $GREEN[✔]"
else
  journal="$WHITE journal $RED[✘]"
fi

exercise=""
cat $todays_note_file 2> /dev/null | grep -i "** exercise" &> /dev/null
if [[ $? == 0 ]]; then
  exercise="$WHITE exercise $GREEN[✔]"
else
  exercise="$WHITE exercise $RED[✘]"
fi

meeting_count=`cat $todays_note_file 2> /dev/null | grep -i "** meeting" | wc -l`
meetings="$WHITE meetings $GREEN $meeting_count"

##from Gary Bernhart
#gitbranch=""
#ref="$(git branch 2> /dev/null | sed -n "/*/ p" | awk '{ print $2 }')"
#if [ -n "$ref" ]; then
#  gitbranch="("${ref#refs/heads/}")"
#fi  

printf "$journal $meditation $lunch $exercise\n$poms $meetings $waters\n$AQUA $(soji status)\n"
