#!/usr/bin/env bash
os_x=`uname -a | fgrep -i 'Darwin'`
if [ "$os_x" != "" ]; then
    crontab -l | { cat; echo "`date -v +45M +'%M %H %d %m *'` soji break15"; } | crontab -
else
    crontab -l | { cat; echo "`date +'%M %H %d %m *' --date '+45 min'` soji break"; } | crontab -
fi

