#!/usr/bin/env bash
soji log "start" "$1"
soji schedule_break15
soji schedule_notification "35 min left! On the task $1" 10
soji schedule_notification "20 min left! On the task $1" 25
soji schedule_notification "10 min left! On the task $1" 35
soji schedule_notification "ONLY 5 min left! On the task $1" 40
soji schedule_notification "Last minute on the task $1" 44
